<Project Sdk="Microsoft.NET.Sdk.Razor">
	<ItemGroup>
		<PackageReference Include="bunit" Version="*" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.*-*" />
		<ProjectReference Include="..\..\src\DesignSystem.Stories\DesignSystem.Stories.csproj" />
	</ItemGroup>
</Project>
